# Generated by Django 4.0.4 on 2022-10-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_itemtable_inventry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
