# Generated by Django 4.0.5 on 2022-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_vendor_statment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts1',
            name='dbbalance',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
