# Generated by Django 4.0.6 on 2022-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_accounts1_dbbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='receivables',
            field=models.FloatField(null=True),
        ),
    ]
