# Generated by Django 4.0.6 on 2022-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_customer_file_customer_receivables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='estimate'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='file_share',
            field=models.FileField(default='', upload_to='estimate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='sales'),
        ),
    ]
