# Generated by Django 4.0.6 on 2022-10-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_estimate_file_alter_estimate_file_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='cid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
