# Generated by Django 4.0.6 on 2022-10-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_alter_invoice_item_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_item',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
