# Generated by Django 4.0.6 on 2022-10-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_estimate_item_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_item',
            name='cid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
